repo_token: SBMdSVwFVDLcXd4wqf7lTFxDEXQvxjgZG
language: node_js
node_js:
- 14

script: echo "Running tests against $(node -v)..."

jobs:
  include:
    - stage: Produce Coverage
      node_js: 14
      script: jest --coverage --coverageReporters=text-lcov|coveralls
