arch: amd64          # optional, this is default, routes to a full VM
os: linux            # optional, this is default
dist: focal          # or bionic | xenial | trusty | precise with xenial as default
language: node_js
node_js:
- 14
- 12

jobs:
  include:
    - stage: Lint
      script: yarn lint
    - stage: build
      script: yarn build
    - stage: Coverage
      script: yarn coverage:ci
