repo_token: Z0ceyY3fx3tzAb7uELcO3I02S7sHEEEe7
language: node_js
node_js:
- "14"
- node

script: echo "Running tests against $(node -v)..."

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: jest --coverage --coverageReporters=text-lcov|coveralls
